name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-js:
    name: lint:js
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup
        uses: ./.github/actions/setup
      - run: pnpm run -r --parallel --aggregate-output lint:js

  lint-types:
    name: lint:types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup
        uses: ./.github/actions/setup
      - run: pnpm run -r --parallel --aggregate-output lint:types

  # test:
  #   name: test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v6
  #     - name: Setup
  #       uses: ./.github/actions/setup
  #     - run: pnpm run -r --parallel --aggregate-output test
